export const HEADER_HEIGHT = '82px'
export const HEADER_MOBILE_HEIGHT = '74px'
export const FOOTER_HEIGHT = '72px'
export const FOOTER_MOBILE_HEIGHT = '68px'
export const COMMENTS_CONTAINER_WIDTH = '500px'
export const AVATAR_WIDTH = '40px'
